name: igcraft
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
  - bioconda
dependencies:
  - python=3.12
  - pip
  - anarci=2024.05.21
  - biopython=1.84
  - pandas=2.2.2
  - pydantic=2.9.2
  - numpy=2.1.2
  - hmmer=3.3.2
  - pytorch>=2.4
  - pytorch-lightning=2.4.0
  - einops=0.8.0
  - hydra-core=1.3.2
  - wandb=0.18.5
  - loguru=0.7.2
  - ipykernel
  - jupyter
  - notebook
  - pip:
      - polars-lts-cpu==1.12.0
      - h5py==3.12.1
      - fast-edit-distance==1.2.2
      - huggingface_hub==0.29.3