# Either a directory containing PDB files or a single PDB file to perform inverse folding on
pdb_path: "data/inverse-folding/test_pdb"

# A CSV file storing PDB IDs (file stem) in the first column and the corresponding chains to inverse
# fold in the second column (as a singe string <VH ID>-<VL ID>).
chain_map: "data/inverse-folding/test_chains.csv"

run_name: "inverse_folding"

checkpoint:
  config_path: "igcraft_model/.hydra/config.yaml"
  checkpoint_path: "igcraft_model/checkpoints/final.ckpt"
  reset_optimizer: false

batch_size: 8
n_sequences: 1
progress_bar: false
seed: 42
out_dir: ${hydra:run.dir}
device: "cuda"

hydra:
  run:
    dir: ${run_name}-${now:%Y-%m-%d-%H-%M-%S}

sampler:
  _target_: igcraft.model.model.PairedSequenceBFNSampler
  vh_len: ${sum:${model.datamodule.vh_tokenizer.region_lengths.fwr1},
    ${model.datamodule.vh_tokenizer.region_lengths.cdr1},
    ${model.datamodule.vh_tokenizer.region_lengths.fwr2},
    ${model.datamodule.vh_tokenizer.region_lengths.cdr2},
    ${model.datamodule.vh_tokenizer.region_lengths.fwr3},
    ${model.datamodule.vh_tokenizer.region_lengths.cdr3},
    ${model.datamodule.vh_tokenizer.region_lengths.fwr4}}
  num_steps: 20
  num_particles: 8
  temperature: 0.1

  solver:
    _target_: igcraft.bfn.bfn.DiscreteBFNSDESolver
    noise_scale: 1.0

## Add fields below to override or add to the existing model config in the checkpoint ##
model:
  cfg:
  
    # override the VH/VL pre-trained weights since those should no longer be loaded
    vh_ckpt_path: null
    vl_ckpt_path: null