run_name: "unconditional_samples"

n_sequences: 2000
batch_size: 50
progress_bar: true
seed: 42
out_dir: ${hydra:run.dir}
device: "cuda"

checkpoint:
  config_path: "igcraft_model/.hydra/config.yaml"
  checkpoint_path: "igcraft_model/checkpoints/final.ckpt"
  reset_optimizer: false

hydra:
  run:
    dir: ${run_name}-${now:%Y-%m-%d-%H-%M-%S}

sampler:

  # Don't touch these
  _target_: igcraft.model.model.PairedSequenceBFNSampler
  vh_len: ${sum:${model.datamodule.vh_tokenizer.region_lengths.fwr1},
    ${model.datamodule.vh_tokenizer.region_lengths.cdr1},
    ${model.datamodule.vh_tokenizer.region_lengths.fwr2},
    ${model.datamodule.vh_tokenizer.region_lengths.cdr2},
    ${model.datamodule.vh_tokenizer.region_lengths.fwr3},
    ${model.datamodule.vh_tokenizer.region_lengths.cdr3},
    ${model.datamodule.vh_tokenizer.region_lengths.fwr4}}
  solver:
    _target_: igcraft.bfn.bfn.DiscreteBFNSDESolver

  # Sampling settings
  num_steps: 20
  num_particles: 32
  temperature: 1.05